### PR TITLE
fix: fix bug where filename contains dot symbol

### PR DESCRIPTION
**Pull request by ckmessi**

### CODE REVIEW

**Comment by jinfagang** [comment]
@ckmessi Did u tested filenames such as `a.jpg.png.jpg`?

**Comment by ckmessi** [comment]
> @ckmessi Did u tested filenames such as `a.jpg.png.jpg`?

Yes, I have tested this case, and it meets the expectation.
In this case, `a.jpg.png` will be treat as a pure file name and the last `.jpg` is the extension.

**Comment by jinfagang** [comment]
@ckmessi I'll merge it.

**Comment by ckmessi** [comment]
> @ckmessi I'll merge it.

Fine, and thank you for the excellent job about this vision tool.

**Pull request merged**
